trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: PortfolioDarkGroup

steps:
- task: DownloadSecureFile@1
  name: configFile
  inputs:
    secureFile: 'config.dev.json'
- task: DownloadSecureFile@1
  name: siteDataFile
  inputs:
    secureFile: 'site-data.dev.json'
- task: DownloadSecureFile@1
  name: portfolioZipFile
  inputs:
    secureFile: 'portfolio.zip'
- task: CopyFiles@2
  name: copyJsons
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '*.json'
    TargetFolder: 'data/'
    OverWrite: true
- task: ExtractFiles@1
  name: extractImages
  inputs:
    archiveFilePatterns: '$(Agent.TempDirectory)/portfolio.zip'
    destinationFolder: 'img/'
    cleanDestinationFolder: true
    overwriteExistingFiles: true
- task: AzureStaticWebApp@0
  inputs:
    app_location: "/"
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: $(deployment_token)
    production_branch: "main"
